# Generated by Django 4.2.3 on 2023-07-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.EmailField(max_length=150, unique=True, verbose_name='Адрес клиента')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('letter_body', models.TextField(max_length=2000, verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало рассылки')),
                ('mailing_stop', models.DateTimeField(blank=True, null=True, verbose_name='Конец рассылки')),
                ('mailing_period', models.CharField(blank=True, choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, null=True, verbose_name='Периодичность')),
                ('status', models.CharField(blank=True, choices=[('created', 'Создана'), ('launched', 'Запущена'), ('completed', 'Завершена')], max_length=10, null=True, verbose_name='Статус рассылки')),
                ('launched_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки рассылки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активация рассылки')),
                ('destination', models.ManyToManyField(blank=True, null=True, to='mailing.client', verbose_name='Клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата попытки')),
                ('attempt_status', models.CharField(blank=True, choices=[('delivered', 'доставлено'), ('not_delivered', 'не доставлено')], max_length=50, null=True, verbose_name='Статус попытки')),
                ('server_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ сервера')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailsetting', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
    ]
