# Generated by Django 4.2.3 on 2023-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsetting',
            name='destination',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиент'),
        ),
    ]
