# Generated by Django 4.2.3 on 2023-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_attempt_options_alter_mailsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='client',
            field=models.ManyToManyField(related_name='clients', to='mailing.client', verbose_name='Клиент'),
        ),
    ]
