# Generated by Django 4.2.3 on 2023-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_options_alter_mailsetting_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата попытки'),
        ),
    ]
