# Generated by Django 4.2.3 on 2023-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_client_author_mailsetting_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsetting',
            options={'permissions': [('can_deactivate_mailing', 'Blocing mailing')], 'verbose_name': 'Рассылка: параметры', 'verbose_name_plural': 'Рассылки: параметры'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email_contact',
            field=models.EmailField(max_length=150, verbose_name='Адрес клиента'),
        ),
    ]
